name: registration_desk
description: Web application for the staff working at the registration desk.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.2.2
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  test: any
  get_it: ^5.0.3

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.0

flutter:
  uses-material-design: true
